version: "2.2"

services:
  client:
    image: yandex/clickhouse-client
    command: ['--host', 'server']
    depends_on:
      - server
  server:
    image: yandex/clickhouse-server
    ports:
      - 8123:8123