version: "3"

services:
  server:
    image: yandex/clickhouse-server
    ports:
      - 8123:8123
    expose:
      - 8123
  client:
    image: yandex/clickhouse-client
    links:
      - server
    depends_on:
      - server
    entrypoint:
      - /bin/sleep
    command:
      - infinity